### ISSUE TITLE
Как убрать точки в оглавлении?

### ISSUE THREAD

**Issue by FirelessWidelity** [Korogodin/NSLReport#7]
Друзья, вопрос с чертежными шрифтами в рамках решен, но Содержание без точек между названием глав и номером страницы никак не поддается. Пишу пояснительную записку. Был бы благодарен в помощи решения данного вопроса.

Пробовал править      
1061: \large \bfseries #1\hfil \hb@xt@\@pnumwidth{\hss #2}}\par
из NSLReport.cls
но безуспешно. Подскажите куда воевать, Chat 3.5 указывает на эту же строку.

**Comment by Korogodin** [comment]
Быстрый поиск дал такой хак:
```
\makeatletter
% Set \@dotsep to a very high value to remove dots
\renewcommand{\@dotsep}{10000}
\makeatother
\tableofcontents
```

Собралось, точек в оглавлении нет, но побочные эффекты не изучены

<img width="304" alt="image" src="https://github.com/Korogodin/NSLReport/assets/747285/da744ce9-3383-43ed-b31f-d4f7062f732b">

**Comment by FirelessWidelity** [comment]
Премного благодарен!
