### ISSUE TITLE
Как изменить верхний отступ?

### ISSUE THREAD

**Issue by FirelessWidelity** [Korogodin/NSLReport#8]
Для `NSLReport` не могу переопределить ` \geometry`. Пробовал менять строку 293 документа 
`NSLExtra`, ничего не изменяется:
`\RequirePackage[right=15mm,top=20mm,bottom=20mm,left=30mm,headsep=0pt,includefoot]{geometry} `
Удалял файлы .aux, накопившиеся в tex/, также безрезультатно.
Затем, после пары часов поиска, решил попробовать переопределить отступ для chapter.
менял вот этот блок кода в NSLReport (484 строка):
` \def\@makechapterhead#1{
   {\parindent \z@ \raggedright \normalfont
    \ifnum \c@secnumdepth >\m@ne
      \hspace{\NSL@ChapterIndent}\NSL@MainChapterStyle
        \centering

      \large \bfseries \thechapter \space
    \fi
    \interlinepenalty\@M
    \NSL@ChapterStyle{#1}\par\nobreak
    \vspace{\NSLAfterTitleSkip}
  }}`
Добавляя вместо пустой строки \vspace и \newline. Результаты и комментарии можете посмотреть здесь:
[stackexchange](https://tex.stackexchange.com/questions/721227/change-the-indentation-before-the-title)

Был бы премного благодарен, не могу пройти нормконтроль

**Comment by Korogodin** [comment]
Если желание поменять верхний отступ текста на всех страницах, то могу предложить поправить в NSLEskd:
```
\textheight=260mm
\headsep=5mm
```
на 
```
\textheight=255mm
\headsep=10mm
```

Можно и через геометрию, но к ней сейчас привязаны координаты линий в рамке. Тогда их поправить соответственно для компенсации изменения геометрии.

Если же стоит задача поправить отступ только перед заголовком главы, то можно посмотреть как это реализовано в NSLBook, там заголовок вообще на пол страницы

**Comment by FirelessWidelity** [comment]
спасибо большое, нормконтроль засчитали, диплом защитил

**Comment by Korogodin** [comment]
> спасибо большое, нормконтроль засчитали, диплом защитил

Мои поздравления!
