### ISSUE TITLE
Inkscape Unknown option -A

### ISSUE THREAD

**Issue by DEFAULTTEXHAPb** [Korogodin/NSLReport#9]
https://github.com/Korogodin/NSLReport/blob/125946029eea014710b9d42d7e8464f732bdc1b2/Makefile#L78

Данная строка в Makefile вызывает ошибку Unknown option -A. Что должна делать опция -A?

**Comment by Korogodin** [comment]
> https://github.com/Korogodin/NSLReport/blob/125946029eea014710b9d42d7e8464f732bdc1b2/Makefile#L78
> 
> Данная строка в Makefile вызывает ошибку Unknown option -A. Что должна делать опция -A?

В новых версиях inkscape ключ A убрали, отсюда эта ошибка. На 78 строчке мекфайла можно заменить на:
```
inkscape --export-filename $(INC)/svg/$*-tmp.pdf $<
```

Если заодно заведете ПР, будет здорово.
